import { useMemo, useState, type FormEvent } from 'react'
import { createWorkspace } from './workspaceApi'
import './Onboarding.css'

type ClassSetup={name:string;sections:string}
export default function Onboarding({complete}:{complete:()=>void}) {
  const [step,setStep]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const [school,setSchool]=useState({name:'',schoolType:'Private',city:'',state:'',country:'India',approximateStudentCount:''})
  const [classes,setClasses]=useState<ClassSetup[]>([{name:'10',sections:'A, B'}])
  const summary=useMemo(()=>classes.filter(x=>x.name.trim()).map(x=>`${x.name}${x.sections.trim()?` · ${x.sections}`:''}`).join(', '),[classes])
  const next=(event:FormEvent)=>{event.preventDefault();setError('');if(step===1&&(!school.name.trim()||!school.city.trim()||!school.state.trim()))return setError('Add your school name, city, and state.');if(step===2&&!classes.some(x=>x.name.trim()))return setError('Add at least one class.');setStep(x=>x+1)}
  const submit=async()=>{setBusy(true);setError('');try{await createWorkspace({...school,approximateStudentCount:Number(school.approximateStudentCount)||null,classes:classes.filter(x=>x.name.trim()).map(x=>({name:x.name.trim(),sections:x.sections.split(',').map(s=>s.trim()).filter(Boolean)}))});complete()}catch(e){setError(e instanceof Error?e.message:'Your workspace could not be created.')}finally{setBusy(false)}}
  return <main className="onboarding"><section className="onboarding-card"><a className="onboarding-brand" href="/">many<span>folds</span></a><div className="onboarding-progress"><i style={{width:`${step/3*100}%`}}/></div><p className="eyebrow">Step {step} of 3</p>{step===1&&<form onSubmit={next}><h1>Set up your school</h1><p>Start with the essentials. You can refine these later.</p><label>School or institution name<input autoFocus value={school.name} onChange={e=>setSchool({...school,name:e.target.value})}/></label><label>School type<select value={school.schoolType} onChange={e=>setSchool({...school,schoolType:e.target.value})}>{['Government','Private','Aided','Other'].map(x=><option key={x}>{x}</option>)}</select></label><div className="onboarding-grid"><label>City<input value={school.city} onChange={e=>setSchool({...school,city:e.target.value})}/></label><label>State<input value={school.state} onChange={e=>setSchool({...school,state:e.target.value})}/></label></div><label>Country<input value={school.country} onChange={e=>setSchool({...school,country:e.target.value})}/></label><button className="new">Continue</button></form>}{step===2&&<form onSubmit={next}><h1>Who do you counsel?</h1><p>Add the classes and the section names your school actually uses.</p>{classes.map((item,index)=><div className="onboarding-class" key={index}><input aria-label="Class" value={item.name} placeholder="Class, e.g. 10" onChange={e=>setClasses(v=>v.map((x,i)=>i===index?{...x,name:e.target.value}:x))}/><input aria-label="Sections" value={item.sections} placeholder="Sections, comma separated" onChange={e=>setClasses(v=>v.map((x,i)=>i===index?{...x,sections:e.target.value}:x))}/>{classes.length>1&&<button type="button" onClick={()=>setClasses(v=>v.filter((_,i)=>i!==index))}>Remove</button>}</div>)}<button type="button" className="secondary" onClick={()=>setClasses(v=>[...v,{name:'',sections:''}])}>Add another class</button><label>Approximate number of students<input type="number" min="0" value={school.approximateStudentCount} onChange={e=>setSchool({...school,approximateStudentCount:e.target.value})}/></label><div className="onboarding-actions"><button type="button" className="secondary" onClick={()=>setStep(1)}>Back</button><button className="new">Continue</button></div></form>}{step===3&&<section><h1>Your workspace is ready to create</h1><p><b>{school.name}</b><br/>{school.city}, {school.state} · {school.country}<br/>{summary||'No classes added'}<br/>{school.approximateStudentCount||'No'} students estimated</p><div className="onboarding-actions"><button className="secondary" onClick={()=>setStep(2)}>Back</button><button className="new" disabled={busy} onClick={()=>void submit()}>{busy?'Creating workspace…':'Create my workspace'}</button></div></section>}{error&&<p className="onboarding-error">{error}</p>}</section></main>
}
